### ISSUE TITLE
Issue with choice used outside an option or command

### ISSUE THREAD

**Issue by shiva** [bcoe/yargs#397]
I wanted to use the choices feature to allow selecting log levels. See below:

```
#!/usr/bin/env node

var argv = require('yargs')
    .alias('l', 'log-level')
    .describe('l', 'Enable and set log level')
    .choices('l', ['info', 'debug', 'error'])
    .default('l', 'error')
    .help('h')
    .alias('h', 'help')
    .argv;
```

I get the following error:

```
~/d/g/f/fix-yaml git:master ❯❯❯ node test.js -h                                                                                                    ✱ ◼
/Users/shiva/dev/github/fix-yaml.git/fix-yaml/test.js:6
    .choices('l', ['info', 'debug', 'error'])
     ^

TypeError: require(...).alias(...).describe(...).choices is not a function
    at Object.<anonymous> (/Users/shiva/dev/github/fix-yaml.git/fix-yaml/test.js:6:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

To troubleshoot this, I tried to write a test, that will specifically test this way of using choices, which however passes.

```
diff --git a/test/yargs.js b/test/yargs.js
index e5be3f3..2f39c2f 100644
--- a/test/yargs.js
+++ b/test/yargs.js
@@ -77,6 +77,17 @@ describe('yargs dsl tests', function () {
     r.errors[0].should.match(/really cool key/)
   })

+  it('access a choice in arguments', function () {
+    var argv = yargs([])
+      .alias('c', 'select-choices')
+      .describe('c', 'select-choices')
+      .choices('c', ['c1', 'c2', 'c3'])
+      .default('c', 'c1')
+      .argv
+
+    argv.selectChoices.should.eql('c1')
+  })
+
   it('treats usage as alias for options, if object provided as first argument', function () {
     var argv = yargs([])
       .usage({
```

Appreciate any help in troubleshooting this usage of choice.

Note it works if I use it this way:

```
#!/usr/bin/env node

var argv = require('yargs')
    .option('log-level', {
        alias: 'l',
        describe: "Enable and set log level",
        choices: ['info', 'debug', 'error'],
        default: 'error'
    })
    .help('h')
    .alias('h', 'help')
	.argv;
```

**Comment by nexdrew** [comment]
@shiva What version of yargs are you using when you get the error? The only way I can reproduce is if I use yargs<=3.15.0. At those versions, the `.choices()` method did not yet exist, and any unknown property given to the `.option()` object will be ignored (and so would not fail).

**Comment by shiva** [comment]
duh. I was using 1.3.2. Apologies. I should have checked that before anything else. My bad.

**Comment by nexdrew** [comment]
@shiva No worries! Happens to the best of us. Thanks for using yargs!
